-- H2 2.2.224;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '96a73544fdf14d12' HASH '92023cb39e3eafd6c7d8f137ba0c566323f1c176d35aadb56c0d5fcdeee442de' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."DAYS"(
    "DAY_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NAME" CHARACTER VARYING(255)
);    
ALTER TABLE "PUBLIC"."DAYS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("DAY_ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DAYS;    
CREATE MEMORY TABLE "PUBLIC"."EVENTS"(
    "EVENT_ID" CHARACTER VARYING(255) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "ENDDATE" TIMESTAMP(6),
    "LOCATION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PUBLICEMAILS" CHARACTER VARYING(255) ARRAY,
    "PUBLICPHONES" BIGINT ARRAY,
    "STARTDATE" TIMESTAMP(6),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "ORG_ID" CHARACTER VARYING(255),
    "USER_ID" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("EVENT_ID"); 
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.EVENTS;  
INSERT INTO "PUBLIC"."EVENTS" VALUES
('977fdc7b-9d58-48ec-aa33-d376e03c4144', 'First event ever! How exciting!!', TIMESTAMP '2024-04-17 14:59:59.387793', 'A planet called Earth', 'First ever event', ARRAY ['PUBLICEMAIL1@email.bu', 'PUBLICEMAIL2@email.bu', 'PUBLICEMAIL2@email.bu'], ARRAY [12345678901, 12345678902, 12345678903], TIMESTAMP '2024-04-17 14:59:59.387793', FALSE, '5', '7'),
('e8374269-76da-4610-9e75-0fc12c3f015a', 'Second is not so bad...', TIMESTAMP '2024-04-17 14:59:59.41479', 'A planet called Mars', 'Not the First ever event', ARRAY ['PUBLICEMAIL12@email.bu', 'PUBLICEMAIL22@email.bu', 'PUBLICEMAIL22@email.bu'], ARRAY [12345433901, 12345458902, 12345656903], TIMESTAMP '2024-04-17 14:59:59.41479', FALSE, '4', '6'),
('a764b4ad-d74b-4ad3-aa1b-6c1e485a301a', 'Ohh we are only third? nevermind will do it', TIMESTAMP '2024-04-17 14:59:59.422785', 'A planet called Venus', 'First ever event! What you say we aren''t??', ARRAY ['PUBLICEMAIL13@email.bu', 'PUBLICEMAIL23@email.bu', 'PUBLICEMAIL23@email.bu'], ARRAY [12343223901, 12343223902, 12343223903], TIMESTAMP '2024-04-17 14:59:59.422785', FALSE, '3', '5'),
('7e32c349-02a9-48ba-b0de-000715fc4f36', 'First event ever! How exciting!!', TIMESTAMP '2024-04-17 15:17:52.78386', 'A planet called Earth', 'First ever event', ARRAY ['PUBLICEMAIL1@email.bu', 'PUBLICEMAIL2@email.bu', 'PUBLICEMAIL2@email.bu'], ARRAY [12345678901, 12345678902, 12345678903], TIMESTAMP '2024-04-17 15:17:52.78386', FALSE, '5', '7'),
('0f0c984c-07ec-4f54-80a9-eb6a6395d913', 'Second is not so bad...', TIMESTAMP '2024-04-17 15:17:52.788864', 'A planet called Mars', 'Not the First ever event', ARRAY ['PUBLICEMAIL12@email.bu', 'PUBLICEMAIL22@email.bu', 'PUBLICEMAIL22@email.bu'], ARRAY [12345433901, 12345458902, 12345656903], TIMESTAMP '2024-04-17 15:17:52.788864', FALSE, '4', '6'),
('1acf4b0e-6db4-4cfc-963c-c6d5150a009b', 'Ohh we are only third? nevermind will do it', TIMESTAMP '2024-04-17 15:17:52.793861', 'A planet called Venus', 'First ever event! What you say we aren''t??', ARRAY ['PUBLICEMAIL13@email.bu', 'PUBLICEMAIL23@email.bu', 'PUBLICEMAIL23@email.bu'], ARRAY [12343223901, 12343223902, 12343223903], TIMESTAMP '2024-04-17 15:17:52.793861', FALSE, '3', '5');
CREATE MEMORY TABLE "PUBLIC"."ITEMS"(
    "ITEM_ID" CHARACTER VARYING(255) NOT NULL,
    "CONDITION" CHARACTER VARYING(255),
    "CREATIONTIME" TIMESTAMP(6),
    "DESCRIPTION" CHARACTER VARYING(255),
    "EMAIL" CHARACTER VARYING(255),
    "LOCATION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PHONE" BIGINT,
    "PRICE" BIGINT,
    "UPDATETIME" TIMESTAMP(6),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "USER_ID" CHARACTER VARYING(255) NOT NULL
);    
ALTER TABLE "PUBLIC"."ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ITEM_ID");   
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.ITEMS;  
INSERT INTO "PUBLIC"."ITEMS" VALUES
('1', 'new', TIMESTAMP '2024-03-19 13:57:35.259333', 'Piros Bicikli', 'email1@mail.bu', 'Budapest', 'bicikli', 342391, 0, TIMESTAMP '2024-03-19 13:57:35.259333', FALSE, '1'),
('2', 'newish', TIMESTAMP '2024-03-19 13:57:35.259333', U&'S\00e1rga Bicikli', 'email2@mail.bu', 'Budapest', 'bicikli', 342391, 71000, TIMESTAMP '2024-03-19 13:57:35.259333', FALSE, '2'),
('3', 'new', TIMESTAMP '2024-03-19 13:57:35.259333', U&'\00c9jjeli Szekr\00e9ny', 'email3@mail.bu', 'Budapest', U&'Szekr\00e9ny', 342391, 23099, TIMESTAMP '2024-03-19 13:57:35.259333', FALSE, '3'),
('4', 'newish', TIMESTAMP '2024-03-19 13:57:35.259333', U&'\00c1gy', 'email4@mail.bu', 'Budapest', U&'\00c1gy', 342391, 10000, TIMESTAMP '2024-03-19 13:57:35.259333', FALSE, '4'),
('5', 'used', TIMESTAMP '2024-03-19 13:57:35.259333', U&'Szinglik a k\00f6rny\00e9keden', 'email5@mail.bu', 'Budapest', 'Szinglik', 342391213424, 0, TIMESTAMP '2024-03-19 13:57:35.259333', FALSE, '5'),
('6', 'new', TIMESTAMP '2024-04-14 00:00:00', U&'Elad\00f3 f\00fcrjek, ketreccel vihet\0151ek', '47658', U&'S\00fcmeg', U&'Elad\00f3 f\00fcrjek, ketreccel vihet\0151ek', 564764654, 1398535, TIMESTAMP '2024-04-14 00:00:00', FALSE, '6'),
('7', 'used', TIMESTAMP '2024-04-14 00:00:00', U&'Samsung hangsz\00f3r\00f3 elad\00f3', '46467', '8554', U&'Samsung hangsz\00f3r\00f3 elad\00f3', 46543, 456456, TIMESTAMP '2024-04-14 00:00:00', FALSE, '7'),
('8', 'new', TIMESTAMP '2024-04-14 00:00:00', U&'\00c9jjeli Szekr\00e9ny', 'email3@mail.bu', 'Budapest', U&'Szekr\00e9ny', 342391, 23099, TIMESTAMP '2024-04-14 00:00:00', FALSE, '1'),
('9', 'newish', TIMESTAMP '2024-04-14 00:00:00', U&'\00c1gy', 'email4@mail.bu', 'Budapest', U&'\00c1gy', 342391, 10000, TIMESTAMP '2024-04-14 00:00:00', FALSE, '2'),
('10', 'newish', TIMESTAMP '2024-04-14 00:00:00', U&'S\00e1rga Bicikli', 'email2@mail.bu', 'Budapest', 'bicikli', 342391, 71000, TIMESTAMP '2024-04-14 00:00:00', FALSE, '3'),
('11', 'new', TIMESTAMP '2024-04-14 00:00:00', U&'Samsung TV ad\00f3 el', '4646567', '8554', U&'Samsung TV ad\00f3 el', 46543, 456456, TIMESTAMP '2024-04-14 00:00:00', FALSE, '4'),
('12', 'new', TIMESTAMP '2024-04-14 00:00:00', U&'IV. Baldwin kir\00e1ly tan\00edt\00e1sai vihet\0151ek', '4646567', '8554', U&'IV. Baldwin kir\00e1ly tan\00edt\00e1sai vihet\0151ek', 46543, 456456, TIMESTAMP '2024-04-14 00:00:00', FALSE, '5'),
('13', 'new', TIMESTAMP '2024-04-14 00:00:00', U&'IV. Baldwin kir\00e1ly tan\00edt\00e1sai vihet\0151ek', '4646567', '8554', U&'IV. Baldwin kir\00e1ly tan\00edt\00e1sai vihet\0151ek', 46543, 456456, TIMESTAMP '2024-04-14 00:00:00', FALSE, '6'),
('14', 'used', TIMESTAMP '2024-04-14 00:00:00', U&'S\00e9r\00fclt szekr\00e9ny elvihet\0151', '47658', 'Budapest', U&'S\00e9r\00fclt szekr\00e9ny elvihet\0151', 564764654, 13535, TIMESTAMP '2024-04-14 00:00:00', FALSE, '7'),
('15', 'new', TIMESTAMP '2024-04-14 00:00:00', U&'LG Monitor elad\00f3', '4646567', '8554', U&'LG Monitor elad\00f3', 46543, 456456, TIMESTAMP '2024-04-14 00:00:00', FALSE, '1'),
('16', 'newish', TIMESTAMP '2024-04-14 00:00:00', U&'Alig haszn\00e1lt \00e9jjeli l\00e1mpa', '12314345', U&'P\00f3csag', U&'Alig haszn\00e1lt \00e9jjeli l\00e1mpa', 243234521, 343215, TIMESTAMP '2024-04-14 00:00:00', FALSE, '2'),
('6e188b11-5dce-4df9-bdcf-f1525920a5b5', 'used', TIMESTAMP '2024-04-17 15:21:28.155579', 'aaaaaaaaaaaaaaa', 'balintlaczko03@gmail.com', 'vvvvvvvvvv', 'bbb', 777, 33, TIMESTAMP '2024-04-17 15:24:36.551712', TRUE, '89f48162-dad3-4f48-bfe5-27f3802c2b11');            
CREATE MEMORY TABLE "PUBLIC"."MYORG_CATEGORIES"(
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "MYORG_ORG_ID" CHARACTER VARYING(255) NOT NULL,
    "CATEGORIES" CHARACTER VARYING(255)
);           
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.MYORG_CATEGORIES;        
INSERT INTO "PUBLIC"."MYORG_CATEGORIES" VALUES
(FALSE, '7', 'DOCTOR'),
(FALSE, '8', 'DOCTOR'),
(FALSE, '9', 'DOCTOR'),
(FALSE, '10', 'DOCTOR'),
(FALSE, '11', 'GOV'),
(FALSE, '12', 'UTILITY');         
CREATE MEMORY TABLE "PUBLIC"."MYORG_RESPONSIBILITIES"(
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "MYORG_ORG_ID" CHARACTER VARYING(255) NOT NULL,
    "RESPONSIBILITIES" CHARACTER VARYING(255)
);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MYORG_RESPONSIBILITIES;  
CREATE MEMORY TABLE "PUBLIC"."NEWS"(
    "NEWS_ID" CHARACTER VARYING(255) NOT NULL,
    "CONTENT" CHARACTER LARGE OBJECT,
    "CREATIONTIME" TIMESTAMP(6),
    "TITLE" CHARACTER LARGE OBJECT,
    "TYPE" CHARACTER VARYING(255),
    "UPDATETIME" TIMESTAMP(6),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "ORG_ID" CHARACTER VARYING(255),
    "USER_ID" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."NEWS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_24" PRIMARY KEY("NEWS_ID");   
-- 27 +/- SELECT COUNT(*) FROM PUBLIC.NEWS;   
INSERT INTO "PUBLIC"."NEWS" VALUES
('0a11aa03-6059-46c2-bb64-b5f9fb2f5e4f', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 14:59:59.428754', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 14:59:59.428754', FALSE, '4', '6'),
('a5b9e05c-6707-4bc5-9acc-f94bc18df0b0', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 14:59:59.433753', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 14:59:59.433753', FALSE, '5', '7'),
('bed4a537-9fdf-4e4c-9ed9-c7532d8ff4f3', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 14:59:59.439784', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 14:59:59.439784', FALSE, '3', '4'),
('1a8b3de1-e189-4669-baaa-01d70cb49182', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 14:59:59.442784', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 14:59:59.442784', FALSE, '2', '4'),
('97c18b92-5005-451c-9349-0b30644901c0', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 14:59:59.444784', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 14:59:59.444784', FALSE, '3', '6'),
('8725305d-4d01-4b16-a0ee-c9648f9ef499', U&'Ism\00e9t \00f6ssze\00fclt a K\00f6nyvek klubja olvas\00f3k\00f6r a Kiskunf\00e9legyh\00e1zi Pet\0151fi S\00e1ndor V\00e1rosi K\00f6nyvt\00e1rban dr. Szab\00f3 Imre filoz\00f3fus vezet\00e9s\00e9vel. A m\00e1rcius 5-ei esem\00e9nyen Oliver Sacks: A f\00e9rfi, aki kalapnak n\00e9zte a feles\00e9g\00e9t c\00edm\0171 m\0171v\00e9t elemezt\00e9k.', TIMESTAMP '2024-04-17 14:59:59.447754', U&'Ism\00e9t \00f6ssze\00fclt a K\00f6nyvek klubja olvas\00f3k\00f6r a k\00f6nyvt\00e1rban', 'LOCAL', TIMESTAMP '2024-04-17 14:59:59.447754', FALSE, '3', '6'),
('b35e0482-2295-4b73-8d70-eba143368aa3', U&'Alap\00edtv\00e1nyi t\00e1mogat\00e1ssal vitte szakmai kir\00e1ndul\00e1sokra 11-12. \00e9vfolyamos di\00e1kjait a K\00f6zg\00e9.', TIMESTAMP '2024-04-17 14:59:59.449754', U&'Szakmai kir\00e1ndul\00e1sok a Nemzeti Egy\00fcttm\0171k\00f6d\00e9si Alap t\00e1mogat\00e1s\00e1val', 'LOCAL', TIMESTAMP '2024-04-17 14:59:59.449754', FALSE, '5', '7'),
('2349780d-3dd1-46b9-ad99-0ba1ed10c55a', U&'Kis-Fekete Vilmos, a Kiskunf\00e9legyh\00e1zi Bal\00e1zs \00c1rp\00e1d Alapfok\00fa M\0171v\00e9szeti Iskola int\00e9zm\00e9nyvezet\0151je tartott el\0151ad\00e1st m\00e1rcius 5-\00e9n, kedden a v\00e1rosi k\00f6nyvt\00e1r baba-mama klubj\00e1ban. A Bet\0171b\00f6lcsiben ez\00fattal a korai hang\00e9lm\00e9nyekr\0151l \00e9s a zenei nevel\00e9s fontoss\00e1g\00e1r\00f3l hallhattak az \00e9rdekl\0151d\0151k.', TIMESTAMP '2024-04-17 14:59:59.454758', U&'Zenei \00e9lm\00e9nyek a Bet\0171b\00f6lcsiben', 'LOCAL', TIMESTAMP '2024-04-17 14:59:59.454758', FALSE, '3', '7'),
('51148f9c-9017-4c69-879d-dab8d538e95d', U&'M\00e1rcius els\0151 h\00e9tv\00e9g\00e9j\00e9n rendezt\00e9k meg Kiskunf\00e9legyh\00e1z\00e1n a XI. Csik\00f3s J\00f3zsef eml\00e9ktorn\00e1t. A sok versenyz\0151 csapatnak k\00f6sz\00f6nhet\0151en 2 helysz\00ednen zajlottak a teremlabdar\00fag\00f3-m\00e9rk\0151z\00e9sek. A F\00e9legyh\00e1zi T\00e9rs\00e9gi Sportiskola U11 koroszt\00e1lya 3 csapatot ind\00edtott a megm\00e9rettet\00e9sen. Az FTSI \201eA\201d \00e9s FTSI \201eB\201d csapat a Kiskunf\00e9legyh\00e1zi V\00e1rosi Sportcsarnokban, a harmadik csapat a Mezg\00e9 sportcsarnok\00e1ban ontotta a g\00f3lokat.', TIMESTAMP '2024-04-17 14:59:59.457755', U&'\00c9remes\0151 a XI. Csik\00f3s J\00f3zsef eml\00e9ktorn\00e1n', 'LOCAL', TIMESTAMP '2024-04-17 14:59:59.457755', FALSE, '1', '4'),
('1b7dc4b6-d705-4e3c-b4b6-93b7332a3ecd', U&'Ism\00e9t \00f6ssze\00fclt a K\00f6nyvek klubja olvas\00f3k\00f6r a Kiskunf\00e9legyh\00e1zi Pet\0151fi S\00e1ndor V\00e1rosi K\00f6nyvt\00e1rban dr. Szab\00f3 Imre filoz\00f3fus vezet\00e9s\00e9vel. A m\00e1rcius 5-ei esem\00e9nyen Oliver Sacks: A f\00e9rfi, aki kalapnak n\00e9zte a feles\00e9g\00e9t c\00edm\0171 m\0171v\00e9t elemezt\00e9k.', TIMESTAMP '2024-04-17 14:59:59.460754', U&'(orsz\00e1gos) Ism\00e9t \00f6ssze\00fclt a K\00f6nyvek klubja olvas\00f3k\00f6r a k\00f6nyvt\00e1rban', 'NATIONAL', TIMESTAMP '2024-04-17 14:59:59.460754', FALSE, '3', '6');         
INSERT INTO "PUBLIC"."NEWS" VALUES
('32503cbb-a74f-46a0-b2be-018abae4f699', U&'Alap\00edtv\00e1nyi t\00e1mogat\00e1ssal vitte szakmai kir\00e1ndul\00e1sokra 11-12. \00e9vfolyamos di\00e1kjait a K\00f6zg\00e9.', TIMESTAMP '2024-04-17 14:59:59.462755', U&'(orsz\00e1gos) Szakmai kir\00e1ndul\00e1sok a Nemzeti Egy\00fcttm\0171k\00f6d\00e9si Alap t\00e1mogat\00e1s\00e1val', 'NATIONAL', TIMESTAMP '2024-04-17 14:59:59.462755', FALSE, '5', '7'),
('5ad2d14d-ff3a-4d2d-ac83-3b249996e84b', U&'Kis-Fekete Vilmos, a Kiskunf\00e9legyh\00e1zi Bal\00e1zs \00c1rp\00e1d Alapfok\00fa M\0171v\00e9szeti Iskola int\00e9zm\00e9nyvezet\0151je tartott el\0151ad\00e1st m\00e1rcius 5-\00e9n, kedden a v\00e1rosi k\00f6nyvt\00e1r baba-mama klubj\00e1ban. A Bet\0171b\00f6lcsiben ez\00fattal a korai hang\00e9lm\00e9nyekr\0151l \00e9s a zenei nevel\00e9s fontoss\00e1g\00e1r\00f3l hallhattak az \00e9rdekl\0151d\0151k.', TIMESTAMP '2024-04-17 14:59:59.464754', U&'(orsz\00e1gos) Zenei \00e9lm\00e9nyek a Bet\0171b\00f6lcsiben', 'NATIONAL', TIMESTAMP '2024-04-17 14:59:59.464754', FALSE, '3', '7'),
('97c62c85-a109-4792-83b6-3a0d77d1569b', U&'M\00e1rcius els\0151 h\00e9tv\00e9g\00e9j\00e9n rendezt\00e9k meg Kiskunf\00e9legyh\00e1z\00e1n a XI. Csik\00f3s J\00f3zsef eml\00e9ktorn\00e1t. A sok versenyz\0151 csapatnak k\00f6sz\00f6nhet\0151en 2 helysz\00ednen zajlottak a teremlabdar\00fag\00f3-m\00e9rk\0151z\00e9sek. A F\00e9legyh\00e1zi T\00e9rs\00e9gi Sportiskola U11 koroszt\00e1lya 3 csapatot ind\00edtott a megm\00e9rettet\00e9sen. Az FTSI \201eA\201d \00e9s FTSI \201eB\201d csapat a Kiskunf\00e9legyh\00e1zi V\00e1rosi Sportcsarnokban, a harmadik csapat a Mezg\00e9 sportcsarnok\00e1ban ontotta a g\00f3lokat.', TIMESTAMP '2024-04-17 14:59:59.466755', U&'(orsz\00e1gos) \00c9remes\0151 a XI. Csik\00f3s J\00f3zsef eml\00e9ktorn\00e1n', 'NATIONAL', TIMESTAMP '2024-04-17 14:59:59.466755', FALSE, '1', '4'),
('355c6e5f-2686-40da-962d-d41a56e55de6', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 15:17:52.79686', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 15:17:52.79686', FALSE, '4', '6'),
('a94f53cf-570c-47e8-ad0e-ee41df61bd06', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 15:17:52.799588', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 15:17:52.799588', FALSE, '5', '7'),
('01c81fc9-8033-4fb8-b3cf-37139678597f', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 15:17:52.802109', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 15:17:52.802109', FALSE, '3', '4'),
('3111e1be-df42-434f-beee-4dd7b177740b', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 15:17:52.808111', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 15:17:52.808111', FALSE, '2', '4'),
('c5de8e2d-b7c9-4079-a467-af1c7d2342bb', 'What could i write thats worthy to be the first? Im not worthy', TIMESTAMP '2024-04-17 15:17:52.809108', 'First ever article!!', 'INTERNATIONAL', TIMESTAMP '2024-04-17 15:17:52.809108', FALSE, '3', '6'),
('f6155fe3-1407-4781-b74b-14c422b8b0da', U&'Ism\00e9t \00f6ssze\00fclt a K\00f6nyvek klubja olvas\00f3k\00f6r a Kiskunf\00e9legyh\00e1zi Pet\0151fi S\00e1ndor V\00e1rosi K\00f6nyvt\00e1rban dr. Szab\00f3 Imre filoz\00f3fus vezet\00e9s\00e9vel. A m\00e1rcius 5-ei esem\00e9nyen Oliver Sacks: A f\00e9rfi, aki kalapnak n\00e9zte a feles\00e9g\00e9t c\00edm\0171 m\0171v\00e9t elemezt\00e9k.', TIMESTAMP '2024-04-17 15:17:52.811108', U&'Ism\00e9t \00f6ssze\00fclt a K\00f6nyvek klubja olvas\00f3k\00f6r a k\00f6nyvt\00e1rban', 'LOCAL', TIMESTAMP '2024-04-17 15:17:52.811108', FALSE, '3', '6'),
('c604541c-fcbd-429a-85f2-03e5b264abce', U&'Alap\00edtv\00e1nyi t\00e1mogat\00e1ssal vitte szakmai kir\00e1ndul\00e1sokra 11-12. \00e9vfolyamos di\00e1kjait a K\00f6zg\00e9.', TIMESTAMP '2024-04-17 15:17:52.813111', U&'Szakmai kir\00e1ndul\00e1sok a Nemzeti Egy\00fcttm\0171k\00f6d\00e9si Alap t\00e1mogat\00e1s\00e1val', 'LOCAL', TIMESTAMP '2024-04-17 15:17:52.813111', FALSE, '5', '7'); 
INSERT INTO "PUBLIC"."NEWS" VALUES
('7fb9c40c-2d90-4f5d-8b24-ed67bd036f59', U&'Kis-Fekete Vilmos, a Kiskunf\00e9legyh\00e1zi Bal\00e1zs \00c1rp\00e1d Alapfok\00fa M\0171v\00e9szeti Iskola int\00e9zm\00e9nyvezet\0151je tartott el\0151ad\00e1st m\00e1rcius 5-\00e9n, kedden a v\00e1rosi k\00f6nyvt\00e1r baba-mama klubj\00e1ban. A Bet\0171b\00f6lcsiben ez\00fattal a korai hang\00e9lm\00e9nyekr\0151l \00e9s a zenei nevel\00e9s fontoss\00e1g\00e1r\00f3l hallhattak az \00e9rdekl\0151d\0151k.', TIMESTAMP '2024-04-17 15:17:52.81511', U&'Zenei \00e9lm\00e9nyek a Bet\0171b\00f6lcsiben', 'LOCAL', TIMESTAMP '2024-04-17 15:17:52.81511', FALSE, '3', '7'),
('b1366638-2ec8-4fc4-bf12-7ed8c0f70932', U&'M\00e1rcius els\0151 h\00e9tv\00e9g\00e9j\00e9n rendezt\00e9k meg Kiskunf\00e9legyh\00e1z\00e1n a XI. Csik\00f3s J\00f3zsef eml\00e9ktorn\00e1t. A sok versenyz\0151 csapatnak k\00f6sz\00f6nhet\0151en 2 helysz\00ednen zajlottak a teremlabdar\00fag\00f3-m\00e9rk\0151z\00e9sek. A F\00e9legyh\00e1zi T\00e9rs\00e9gi Sportiskola U11 koroszt\00e1lya 3 csapatot ind\00edtott a megm\00e9rettet\00e9sen. Az FTSI \201eA\201d \00e9s FTSI \201eB\201d csapat a Kiskunf\00e9legyh\00e1zi V\00e1rosi Sportcsarnokban, a harmadik csapat a Mezg\00e9 sportcsarnok\00e1ban ontotta a g\00f3lokat.', TIMESTAMP '2024-04-17 15:17:52.819109', U&'\00c9remes\0151 a XI. Csik\00f3s J\00f3zsef eml\00e9ktorn\00e1n', 'LOCAL', TIMESTAMP '2024-04-17 15:17:52.819109', FALSE, '1', '4'),
('de7206b4-279c-4fab-b98d-99ec3ca11d2c', U&'Ism\00e9t \00f6ssze\00fclt a K\00f6nyvek klubja olvas\00f3k\00f6r a Kiskunf\00e9legyh\00e1zi Pet\0151fi S\00e1ndor V\00e1rosi K\00f6nyvt\00e1rban dr. Szab\00f3 Imre filoz\00f3fus vezet\00e9s\00e9vel. A m\00e1rcius 5-ei esem\00e9nyen Oliver Sacks: A f\00e9rfi, aki kalapnak n\00e9zte a feles\00e9g\00e9t c\00edm\0171 m\0171v\00e9t elemezt\00e9k.', TIMESTAMP '2024-04-17 15:17:52.825127', U&'(orsz\00e1gos) Ism\00e9t \00f6ssze\00fclt a K\00f6nyvek klubja olvas\00f3k\00f6r a k\00f6nyvt\00e1rban', 'NATIONAL', TIMESTAMP '2024-04-17 15:17:52.825127', FALSE, '3', '6'),
('ed726182-ff1a-4c58-b875-6be676a7e962', U&'Alap\00edtv\00e1nyi t\00e1mogat\00e1ssal vitte szakmai kir\00e1ndul\00e1sokra 11-12. \00e9vfolyamos di\00e1kjait a K\00f6zg\00e9.', TIMESTAMP '2024-04-17 15:17:52.82711', U&'(orsz\00e1gos) Szakmai kir\00e1ndul\00e1sok a Nemzeti Egy\00fcttm\0171k\00f6d\00e9si Alap t\00e1mogat\00e1s\00e1val', 'NATIONAL', TIMESTAMP '2024-04-17 15:17:52.82711', FALSE, '5', '7'),
('1143ed30-3bf1-4ab5-9b17-771d27498287', U&'Kis-Fekete Vilmos, a Kiskunf\00e9legyh\00e1zi Bal\00e1zs \00c1rp\00e1d Alapfok\00fa M\0171v\00e9szeti Iskola int\00e9zm\00e9nyvezet\0151je tartott el\0151ad\00e1st m\00e1rcius 5-\00e9n, kedden a v\00e1rosi k\00f6nyvt\00e1r baba-mama klubj\00e1ban. A Bet\0171b\00f6lcsiben ez\00fattal a korai hang\00e9lm\00e9nyekr\0151l \00e9s a zenei nevel\00e9s fontoss\00e1g\00e1r\00f3l hallhattak az \00e9rdekl\0151d\0151k.', TIMESTAMP '2024-04-17 15:17:52.830918', U&'(orsz\00e1gos) Zenei \00e9lm\00e9nyek a Bet\0171b\00f6lcsiben', 'NATIONAL', TIMESTAMP '2024-04-17 15:17:52.830918', FALSE, '3', '7'),
('cf02a76e-0abd-40cc-97d3-554055e7080f', U&'M\00e1rcius els\0151 h\00e9tv\00e9g\00e9j\00e9n rendezt\00e9k meg Kiskunf\00e9legyh\00e1z\00e1n a XI. Csik\00f3s J\00f3zsef eml\00e9ktorn\00e1t. A sok versenyz\0151 csapatnak k\00f6sz\00f6nhet\0151en 2 helysz\00ednen zajlottak a teremlabdar\00fag\00f3-m\00e9rk\0151z\00e9sek. A F\00e9legyh\00e1zi T\00e9rs\00e9gi Sportiskola U11 koroszt\00e1lya 3 csapatot ind\00edtott a megm\00e9rettet\00e9sen. Az FTSI \201eA\201d \00e9s FTSI \201eB\201d csapat a Kiskunf\00e9legyh\00e1zi V\00e1rosi Sportcsarnokban, a harmadik csapat a Mezg\00e9 sportcsarnok\00e1ban ontotta a g\00f3lokat.', TIMESTAMP '2024-04-17 15:17:52.832928', U&'(orsz\00e1gos) \00c9remes\0151 a XI. Csik\00f3s J\00f3zsef eml\00e9ktorn\00e1n', 'NATIONAL', TIMESTAMP '2024-04-17 15:17:52.832928', FALSE, '1', '4'),
('ce907cc7-7362-4f8b-acab-23c1728ee532', 'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww wwwwwwwwwwwwww w  wwwwwwwwww', TIMESTAMP '2024-04-17 15:27:35.72756', U&'Olcs\00f3 a csirkefarh\00e1t a tescdoban', 'LOCAL', TIMESTAMP '2024-04-17 15:27:35.72756', FALSE, '3', '6');             
CREATE MEMORY TABLE "PUBLIC"."NOTICES"(
    "NOTICE_ID" CHARACTER VARYING(255) NOT NULL,
    "DATE" TIMESTAMP(6),
    "DESCRIPTION" CHARACTER VARYING(255),
    "LOCATION" CHARACTER VARYING(255),
    "PHONE" BIGINT,
    "TYPE" CHARACTER VARYING(255),
    "URGENCY" CHARACTER VARYING(255),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "USER_ID" CHARACTER VARYING(255) NOT NULL
);    
ALTER TABLE "PUBLIC"."NOTICES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A9" PRIMARY KEY("NOTICE_ID");              
-- 26 +/- SELECT COUNT(*) FROM PUBLIC.NOTICES;
INSERT INTO "PUBLIC"."NOTICES" VALUES
('ec8deb00-ec53-4076-bb67-ca3402f9d2c2', TIMESTAMP '2024-04-17 01:20:00', 'hip', '543tg', 21234, 'KOZTERULET', '1', FALSE, '1'),
('3926e198-36a1-4457-aa42-48af87f1c7c6', TIMESTAMP '2024-04-17 01:20:00', 'hip', '543tg', 21234, 'KOZTERULET', '1', FALSE, '2'),
('ef0c4408-7f6a-45fc-8bee-0974261b431c', TIMESTAMP '2024-04-19 01:20:00', 'hip', '543tg', 21234, 'UTHIBA', '2', FALSE, '3'),
('7832d779-cc26-4215-b9de-427c6f6e65a0', TIMESTAMP '2024-04-19 01:20:00', 'hip', '543tg', 21234, 'UTHIBA', '2', FALSE, '4'),
('df6cd820-165e-4078-a556-bb9f055465b0', TIMESTAMP '2024-04-20 01:20:00', 'hip', '543tg', 21234, 'VIZGAZ', '3', FALSE, '5'),
('6b5faca3-62ed-4a2e-8dcd-fb0d898b04d4', TIMESTAMP '2024-04-20 01:20:00', 'hip', '543tg', 21234, 'VIZGAZ', '3', FALSE, '6'),
('24b2b610-6f38-4663-9f68-9b00ed343cbc', TIMESTAMP '2024-04-21 01:20:00', 'hip', '543tg', 21234, 'LOMTALANITAS', '4', FALSE, '7'),
('70a3cd9d-b54e-4b78-b2df-34cbae9f3b37', TIMESTAMP '2024-04-21 01:20:00', 'hip', '543tg', 21234, 'LOMTALANITAS', '4', FALSE, '1'),
('7fbe1dcb-0da6-4d7c-8d66-233212e8bda8', TIMESTAMP '2024-04-22 01:20:00', 'hip', '543tg', 21234, 'SZEMETSZALLITAS', '1', FALSE, '2'),
('0064a7cc-a2be-451d-ad9a-91f99fa72bec', TIMESTAMP '2024-04-22 01:20:00', 'hip', '543tg', 21234, 'SZEMETSZALLITAS', '1', FALSE, '3'),
('a3778b3d-9e1b-4295-99f6-5e193ed02ede', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'KOZTERULET', '2', FALSE, '4'),
('687ecc78-2bae-431c-90a3-184e781ee833', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'KOZTERULET', '2', FALSE, '5'),
('6544864b-0623-4631-a53f-b794828b9c03', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'UTHIBA', '2', FALSE, '6'),
('351604e3-3dbe-4870-a93c-e5a5d70b48db', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'UTHIBA', '2', FALSE, '7'),
('e5095f66-be50-44fd-8b28-0c3b238bc6d1', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'VIZGAZ', '2', FALSE, '1'),
('33e178d8-139a-4fde-9cf0-9508877954e8', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'VIZGAZ', '2', FALSE, '2'),
('d5921ff8-78c9-475f-90f9-5fc538d74c94', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'LOMTALANITAS', '2', FALSE, '3'),
('0d9cd84a-aac2-4d54-951b-ab6009457d38', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'LOMTALANITAS', '2', FALSE, '4'),
('a8acd980-2cf3-4250-9c02-22f59bd9fa70', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'SZEMETSZALLITAS', '2', FALSE, '5'),
('e855252b-59cd-4cf7-bf50-598c77607afb', TIMESTAMP '2024-04-23 01:20:00', 'hip', '543tg', 21234, 'SZEMETSZALLITAS', '2', FALSE, '6'),
('28b237fb-cf3e-4494-ac92-4243ac804af9', TIMESTAMP '2024-04-17 14:59:59.467755', 'There is an alien SpaceShip parked in front of our house illegaly', 'our address', 12345678901, 'KOZTERULET', '3', FALSE, '5'),
('0060ee84-91a6-4d8d-a40f-44937d82db5a', TIMESTAMP '2024-04-17 14:59:59.474756', 'There is an alien SpaceShip parked in front of our house illegaly', 'our address', 12345678901, 'KOZTERULET', '3', FALSE, '2'),
('c7ffcffc-e93f-4b09-b5ac-7eb4fae7be0c', TIMESTAMP '2024-04-17 14:59:59.478759', 'There is an alien SpaceShip parked in front of our house illegaly', 'our address', 12345678901, 'KOZTERULET', '2', FALSE, '3'),
('16eeeadd-9be0-474f-8f66-c08f5fb03960', TIMESTAMP '2024-04-17 15:17:52.833928', 'There is an alien SpaceShip parked in front of our house illegaly', 'our address', 12345678901, 'KOZTERULET', '3', FALSE, '5'),
('95d9ba5a-b94a-4412-9570-d0abf96846f6', TIMESTAMP '2024-04-17 15:17:52.838948', 'There is an alien SpaceShip parked in front of our house illegaly', 'our address', 12345678901, 'KOZTERULET', '3', FALSE, '2'),
('498c2f92-0dd3-4bd3-b731-c68718ddaf0b', TIMESTAMP '2024-04-17 15:17:52.84293', 'There is an alien SpaceShip parked in front of our house illegaly', 'our address', 12345678901, 'KOZTERULET', '2', FALSE, '3');    
CREATE MEMORY TABLE "PUBLIC"."ORGANISATIONS"(
    "ORG_ID" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL
);          
ALTER TABLE "PUBLIC"."ORGANISATIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ORG_ID");            
-- 12 +/- SELECT COUNT(*) FROM PUBLIC.ORGANISATIONS;          
INSERT INTO "PUBLIC"."ORGANISATIONS" VALUES
('1', 'FirstOrg', FALSE),
('2', 'SecondOrg', FALSE),
('3', 'ThirdOrg', FALSE),
('4', 'OrgAdmins org', FALSE),
('5', 'adminOrgAdmins org', FALSE),
('6', 'just some org', FALSE),
('7', U&'Dr. Baka K\00e1roly: Kardiol\00f3gus', FALSE),
('8', U&'Dr. Osb\00e1th L\00e1szl\00f3: H\00e1ziorvos', FALSE),
('9', U&'Dr. Kun B\00e9la: Seb\00e9sz', FALSE),
('10', U&'Dr. Mad\00e1r Katalin: H\00e1ziorvos', FALSE),
('11', U&'Helyi \00d6nkorm\00e1nyzat', FALSE),
('12', U&'K\00f6zm\0171vek', FALSE); 
CREATE MEMORY TABLE "PUBLIC"."ORGS_ADMINS"(
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "USER_ID" CHARACTER VARYING(255) NOT NULL,
    "ORG_ID" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."ORGS_ADMINS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_13" PRIMARY KEY("USER_ID", "ORG_ID");  
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.ORGS_ADMINS;             
INSERT INTO "PUBLIC"."ORGS_ADMINS" VALUES
(FALSE, '6', '4'),
(FALSE, '6', '1'),
(FALSE, '6', '2'),
(FALSE, '6', '3'),
(FALSE, '7', '5'),
(FALSE, '7', '1'),
(FALSE, '7', '2'),
(FALSE, '7', '3');     
CREATE MEMORY TABLE "PUBLIC"."POSTS"(
    "POST_ID" CHARACTER VARYING(255) NOT NULL,
    "CONTENT" CHARACTER VARYING(255),
    "CREATIONTIME" TIMESTAMP(6),
    "DISLIKES" BIGINT DEFAULT 0,
    "LIKES" BIGINT DEFAULT 0,
    "UPDATETIME" TIMESTAMP(6),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "ORG_ID" CHARACTER VARYING(255),
    "USER_ID" CHARACTER VARYING(255) NOT NULL,
    "VOTE_ID" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."POSTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_48" PRIMARY KEY("POST_ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POSTS;   
CREATE MEMORY TABLE "PUBLIC"."RESERVATIONS"(
    "RESERVATION_ID" CHARACTER VARYING(255) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "ENDDATE" TIMESTAMP(6),
    "PHONE" BIGINT,
    "PREFERREDNAME" CHARACTER VARYING(255),
    "STARTDATE" TIMESTAMP(6),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "ORG_ID" CHARACTER VARYING(255),
    "USER_ID" CHARACTER VARYING(255) NOT NULL
);              
ALTER TABLE "PUBLIC"."RESERVATIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_41" PRIMARY KEY("RESERVATION_ID");    
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.RESERVATIONS;            
INSERT INTO "PUBLIC"."RESERVATIONS" VALUES
('6bb860f6-af88-4332-9349-e65a7469292a', 'billspublicemail@email.bu', TIMESTAMP '2024-04-17 14:59:59.481754', 123456780, 'Bill', TIMESTAMP '2024-04-17 14:59:59.481754', FALSE, '6', '1'),
('b1bda6f7-cb22-4cf1-8ad4-b6613bfbdf85', 'marispublicemail@email.bu', TIMESTAMP '2024-04-17 14:59:59.489755', 123456780, 'Mari', TIMESTAMP '2024-04-17 14:59:59.489755', FALSE, '5', '3'),
('75e11df6-6d44-46b0-a6ad-c1caea43c556', 'balintspublicemail@email.bu', TIMESTAMP '2024-04-17 14:59:59.492241', 123456780, U&'B\00e1lint', TIMESTAMP '2024-04-17 14:59:59.492241', FALSE, '4', '2'),
('243c27f1-1c26-486b-8365-b9f53cfe018e', 'billspublicemail@email.bu', TIMESTAMP '2024-04-17 15:17:52.846993', 123456780, 'Bill', TIMESTAMP '2024-04-17 15:17:52.846993', FALSE, '6', '1'),
('46445a9c-a5e3-4c79-8ccd-136c64c4a9fe', 'marispublicemail@email.bu', TIMESTAMP '2024-04-17 15:17:52.851994', 123456780, 'Mari', TIMESTAMP '2024-04-17 15:17:52.851994', FALSE, '5', '3'),
('1f9796c6-e78e-4e25-9226-5cbacf46f8b1', 'balintspublicemail@email.bu', TIMESTAMP '2024-04-17 15:17:52.856998', 123456780, U&'B\00e1lint', TIMESTAMP '2024-04-17 15:17:52.856998', FALSE, '4', '2');        
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "USER_ID" CHARACTER VARYING(255) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "FIRSTNAME" CHARACTER VARYING(255),
    "LASTNAME" CHARACTER VARYING(255),
    "PHONE" BIGINT,
    "USERNAME" CHARACTER VARYING(255),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL
);  
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("USER_ID");  
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
('1', 'bbb@ccc.bu', U&'\00c1kos', U&'Kov\00e1cs', 303345677, 'moba', FALSE),
('2', 'aaa@ddd.bu', U&'J\00f3ska', 'Kiss', 1130322677, 'Blob', FALSE),
('3', 'ccc@eee.bu', 'Mira', 'Nagy', 4456345677, 'Eevee', FALSE),
('4', 'admin@email.bu', 'Admin', 'Admin', 303345677, 'admin', FALSE),
('5', 'user@email.bu', 'User', 'User', 303345677, 'user', FALSE),
('6', 'orgadmin@email.bu', 'OrgAdmin', 'OrgAdmin', 303345677, 'orgadmin', FALSE),
('7', 'adminorgadmin@email.bu', 'adminOrgAdmin', 'adminOrgAdmin', 303345677, 'adminorgadmin', FALSE),
('89f48162-dad3-4f48-bfe5-27f3802c2b11', 'KittyCica@gmail.com', 'Kitty', 'Cica', 777, 'Cica', FALSE);        
CREATE MEMORY TABLE "PUBLIC"."VOTE_OPTIONS"(
    "VOTE_OPTION_ID" CHARACTER VARYING(255) NOT NULL,
    "OPTIONTEXT" CHARACTER VARYING(255),
    "VOTESNUM" BIGINT DEFAULT 0,
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "VOTE_ID" CHARACTER VARYING(255)
);    
ALTER TABLE "PUBLIC"."VOTE_OPTIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_13A" PRIMARY KEY("VOTE_OPTION_ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VOTE_OPTIONS;            
CREATE MEMORY TABLE "PUBLIC"."VOTES"(
    "VOTE_ID" CHARACTER VARYING(255) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "DELETED" BOOLEAN COMMENT 'Soft-delete indicator' NOT NULL,
    "POST_ID" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."VOTES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4E" PRIMARY KEY("VOTE_ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VOTES;   
ALTER TABLE "PUBLIC"."NOTICES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" CHECK("TYPE" IN('KOZTERULET', 'UTHIBA', 'VIZGAZ', 'LOMTALANITAS', 'SZEMETSZALLITAS')) NOCHECK;          
ALTER TABLE "PUBLIC"."NEWS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" CHECK("TYPE" IN('LOCAL', 'NATIONAL', 'INTERNATIONAL')) NOCHECK;            
ALTER TABLE "PUBLIC"."MYORG_RESPONSIBILITIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7F" CHECK("RESPONSIBILITIES" IN('KOZTERULET', 'UTHIBA', 'VIZGAZ', 'LOMTALANITAS', 'SZEMETSZALLITAS')) NOCHECK;              
ALTER TABLE "PUBLIC"."MYORG_CATEGORIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" CHECK("CATEGORIES" IN('DOCTOR', 'UTILITY', 'GOV')) NOCHECK;    
ALTER TABLE "PUBLIC"."VOTES" ADD CONSTRAINT "PUBLIC"."UK_SNOWCFFJECRW34FXM6H5FYAH4" UNIQUE("POST_ID");        
ALTER TABLE "PUBLIC"."POSTS" ADD CONSTRAINT "PUBLIC"."UK_D29HLAA44KP8QEUU7JEM73PYS" UNIQUE("VOTE_ID");        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UK_SX468G52BPETVLAD2J9Y0LPTC" UNIQUE("EMAIL", "USERNAME");              
ALTER TABLE "PUBLIC"."ORGS_ADMINS" ADD CONSTRAINT "PUBLIC"."FKTGA9INJN0M3JKVMBUKJ14NBVG" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;               
ALTER TABLE "PUBLIC"."MYORG_RESPONSIBILITIES" ADD CONSTRAINT "PUBLIC"."FKPMR5TOIODT0JUDYAWGY449BGU" FOREIGN KEY("MYORG_ORG_ID") REFERENCES "PUBLIC"."ORGANISATIONS"("ORG_ID") NOCHECK;        
ALTER TABLE "PUBLIC"."RESERVATIONS" ADD CONSTRAINT "PUBLIC"."FKR7FRB3B9LHJXCCLMWHNN7W5XL" FOREIGN KEY("ORG_ID") REFERENCES "PUBLIC"."ORGANISATIONS"("ORG_ID") NOCHECK;        
ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "PUBLIC"."FKL55PI3HK9993UYM4Q3RGGWQ3Y" FOREIGN KEY("ORG_ID") REFERENCES "PUBLIC"."ORGANISATIONS"("ORG_ID") NOCHECK;              
ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "PUBLIC"."FKAT8P3S7YJCP57LNY4UDQVQNCQ" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;    
ALTER TABLE "PUBLIC"."POSTS" ADD CONSTRAINT "PUBLIC"."FK5LIDM6CQBC7U4XHQPXM898QME" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;     
ALTER TABLE "PUBLIC"."POSTS" ADD CONSTRAINT "PUBLIC"."FKSAKBL9CJ1Y08B0W4E9FNQAY6C" FOREIGN KEY("VOTE_ID") REFERENCES "PUBLIC"."VOTES"("VOTE_ID") NOCHECK;     
ALTER TABLE "PUBLIC"."RESERVATIONS" ADD CONSTRAINT "PUBLIC"."FKB5G9IO5H54IWL2INKNO50PPLN" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;              
ALTER TABLE "PUBLIC"."ORGS_ADMINS" ADD CONSTRAINT "PUBLIC"."FKSNJFOBGPLP4F8P2YC3E2PW76W" FOREIGN KEY("ORG_ID") REFERENCES "PUBLIC"."ORGANISATIONS"("ORG_ID") NOCHECK;         
ALTER TABLE "PUBLIC"."MYORG_CATEGORIES" ADD CONSTRAINT "PUBLIC"."FK6J6CEF3TAAST2EDOF0E2NTF3F" FOREIGN KEY("MYORG_ORG_ID") REFERENCES "PUBLIC"."ORGANISATIONS"("ORG_ID") NOCHECK;              
ALTER TABLE "PUBLIC"."NOTICES" ADD CONSTRAINT "PUBLIC"."FKERQKXCII6JCL64MUYRCXM10SP" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;   
ALTER TABLE "PUBLIC"."POSTS" ADD CONSTRAINT "PUBLIC"."FK1Y0SKI82N2JL0VQMVDMVC1HG6" FOREIGN KEY("ORG_ID") REFERENCES "PUBLIC"."ORGANISATIONS"("ORG_ID") NOCHECK;               
ALTER TABLE "PUBLIC"."ITEMS" ADD CONSTRAINT "PUBLIC"."FKFT8PMHNDQ1KNTVYFAQCYBHXVX" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;     
ALTER TABLE "PUBLIC"."NEWS" ADD CONSTRAINT "PUBLIC"."FK30X0H6UEEPMP9HS6BUSUMUHWP" FOREIGN KEY("ORG_ID") REFERENCES "PUBLIC"."ORGANISATIONS"("ORG_ID") NOCHECK;
ALTER TABLE "PUBLIC"."NEWS" ADD CONSTRAINT "PUBLIC"."FKI09N75TXTUDW1KAWJ5O7I8XAG" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;      
ALTER TABLE "PUBLIC"."VOTE_OPTIONS" ADD CONSTRAINT "PUBLIC"."FKL2AKX1LLL3M5B004Q80729OUI" FOREIGN KEY("VOTE_ID") REFERENCES "PUBLIC"."VOTES"("VOTE_ID") NOCHECK;              
ALTER TABLE "PUBLIC"."VOTES" ADD CONSTRAINT "PUBLIC"."FK1M2JQTRO85C13YA5KV0KVKC97" FOREIGN KEY("POST_ID") REFERENCES "PUBLIC"."POSTS"("POST_ID") NOCHECK;     
